## ags_gui.gd — GUI runtime for AGS3D (T-GS14)
##
## Attach to the root CanvasLayer node generated by ag build from a .agui file.
## Add the generated .agui scene as an AutoLoad in the Godot project so it
## persists across room transitions.
##
## The script locates child widgets by their metadata/ags_widget tag
## (written by the scene generator) and wires them to AGSRuntime:
##
##   InventoryBar (GridContainer) — rebuilt whenever the player's inventory changes.
##   VerbBar      (HBoxContainer) — verb buttons; pressing one calls set_active_verb().
##   StatusLine   (Label)         — text set by AGSRuntime.set_status_text().
##
## No icon loading is implemented for InventoryBar in this release; items are shown
## as text buttons. A future task will wire AGSItem.icon to the slot texture.
extends CanvasLayer

var _inv_bar: GridContainer = null
var _verb_bar: HBoxContainer = null
var _status_line: Label = null

## Last inventory snapshot for change-detection (avoids rebuilding every frame).
var _last_inventory: Array = []


func _ready() -> void:
	_locate_widgets()
	AGSRuntime.status_text_changed.connect(_on_status_text_changed)
	AGSRuntime.active_verb_changed.connect(_on_active_verb_changed)


func _process(_delta: float) -> void:
	_refresh_inventory()


# --------------------------------------------------------------------------
# Widget discovery
# --------------------------------------------------------------------------

func _locate_widgets() -> void:
	for child in get_children():
		var wtype: String = child.get_meta("ags_widget", "")
		match wtype:
			"InventoryBar":
				_inv_bar = child as GridContainer
			"VerbBar":
				_verb_bar = child as HBoxContainer
				_wire_verb_buttons()
			"StatusLine":
				_status_line = child as Label


# --------------------------------------------------------------------------
# VerbBar
# --------------------------------------------------------------------------

func _wire_verb_buttons() -> void:
	if _verb_bar == null:
		return
	for btn in _verb_bar.get_children():
		if btn is Button:
			var verb: String = btn.get_meta("ags_verb", "")
			btn.pressed.connect(func() -> void: _on_verb_pressed(verb))


func _on_verb_pressed(verb: String) -> void:
	AGSRuntime.set_active_verb(verb)


func _on_active_verb_changed(verb: String) -> void:
	if _verb_bar == null:
		return
	for btn in _verb_bar.get_children():
		if btn is Button:
			btn.button_pressed = (btn.get_meta("ags_verb", "") == verb)


# --------------------------------------------------------------------------
# StatusLine
# --------------------------------------------------------------------------

func _on_status_text_changed(text: String) -> void:
	if _status_line != null:
		_status_line.text = text


# --------------------------------------------------------------------------
# InventoryBar
# --------------------------------------------------------------------------

func _refresh_inventory() -> void:
	if _inv_bar == null:
		return
	var player_name := str(AGSRuntime.get_global("player"))
	if player_name.is_empty():
		return
	var player := AGSRuntime.get_character(player_name) as AGSCharacterBase
	if player == null or not player.has_method("get_inventory"):
		return
	var inv: Array = player.call("get_inventory")
	if inv == _last_inventory:
		return
	_last_inventory = inv.duplicate()
	_rebuild_inventory_bar(inv)


func _rebuild_inventory_bar(inv: Array) -> void:
	for child in _inv_bar.get_children():
		child.queue_free()
	var item_size: Vector2i = _inv_bar.get_meta("item_size", Vector2i(48, 48))
	for item_name in inv:
		var btn := Button.new()
		btn.text = str(item_name)
		btn.custom_minimum_size = Vector2(item_size.x, item_size.y)
		_inv_bar.add_child(btn)
