#pragma once

#include "core/io/resource_loader.h"
#include "modules/gdscript/gdscript.h"

// ResourceFormatLoaderAGSEmbed serves embedded GDScripts from C++ string constants.
// It intercepts load requests for res://.engine/runtime/*.gd paths and returns
// GDScript objects populated from embedded source strings instead of disk files.
//
// To add/update embedded scripts:
//   1. Edit embedded_scripts_strings.h (generated by tools/embed_scripts/main.go)
//   2. Or add strings directly to ags_embed_strings.cpp
//   3. Include ags_embed_strings.cpp in SCsub
class ResourceFormatLoaderAGSEmbed : public ResourceFormatLoader {
	GDCLASS(ResourceFormatLoaderAGSEmbed, ResourceFormatLoader);

	struct EmbeddedScript {
		String path;
		String source;
	};

	Vector<EmbeddedScript> _scripts;

	String _get_embedded_source(const String &p_path) const;

public:
	bool handles_type(const String &p_type) const override;
	bool recognize_path(const String &p_path, const String &p_for_type) const override;
	Ref<Resource> load(const String &p_path, const String &p_for_type,
			bool p_no_cache, bool p_use_sub_threads, float *r_progress,
			CacheMode p_cache_mode) override;
	void get_recognized_extensions(List<String> *p_extensions) const override;
	String get_resource_type(const String &p_path) const override;
	void get_dependencies(const String &p_path,
			HashMap<String, HashSet<String>> &p_dependencies, int p_depth) override;

	// Called by ags_embed_strings.cpp during module init to register scripts.
	void register_script(const String &p_path, const String &p_source);
	Vector<String> get_embedded_paths() const;

	ResourceFormatLoaderAGSEmbed();
	~ResourceFormatLoaderAGSEmbed();
};
