// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {api} from '../models';

export function BatchViz(arg1:Array<string>,arg2:string):Promise<number>;

export function Build():Promise<string>;

export function GenerateCharScene(arg1:string):Promise<string>;

export function GenerateRoomScene(arg1:string):Promise<string>;

export function ListRefFiles(arg1:string):Promise<Array<main.SourceFile>>;

export function ListSourceFiles():Promise<Array<main.SourceFile>>;

export function LoadProject(arg1:string):Promise<main.ProjectInfo>;

export function OpenProject():Promise<main.ProjectInfo>;

export function OpenRefFolder():Promise<main.RefFolderInfo>;

export function ParseChar(arg1:string):Promise<api.ParsedChar>;

export function ParseRoom(arg1:string):Promise<api.ParsedRoom>;

export function ReadFile(arg1:string):Promise<string>;

export function TranspileFile(arg1:string):Promise<main.TranspileResult>;

export function ValidateProject():Promise<api.ValidateResult>;

export function VizAST(arg1:string):Promise<string>;

export function VizASTDot(arg1:string):Promise<string>;

export function VizBlocking(arg1:string):Promise<string>;

export function VizEmit(arg1:string):Promise<string>;

export function VizSymbols(arg1:string):Promise<string>;

export function VizSymbolsDot(arg1:string):Promise<string>;

export function VizTokens(arg1:string):Promise<string>;
