// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchViz(arg1, arg2) {
  return window['go']['main']['App']['BatchViz'](arg1, arg2);
}

export function Build() {
  return window['go']['main']['App']['Build']();
}

export function GenerateCharScene(arg1) {
  return window['go']['main']['App']['GenerateCharScene'](arg1);
}

export function GenerateRoomScene(arg1) {
  return window['go']['main']['App']['GenerateRoomScene'](arg1);
}

export function ListRefFiles(arg1) {
  return window['go']['main']['App']['ListRefFiles'](arg1);
}

export function ListSourceFiles() {
  return window['go']['main']['App']['ListSourceFiles']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function OpenProject() {
  return window['go']['main']['App']['OpenProject']();
}

export function OpenRefFolder() {
  return window['go']['main']['App']['OpenRefFolder']();
}

export function ParseChar(arg1) {
  return window['go']['main']['App']['ParseChar'](arg1);
}

export function ParseRoom(arg1) {
  return window['go']['main']['App']['ParseRoom'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function TranspileFile(arg1) {
  return window['go']['main']['App']['TranspileFile'](arg1);
}

export function ValidateProject() {
  return window['go']['main']['App']['ValidateProject']();
}

export function VizAST(arg1) {
  return window['go']['main']['App']['VizAST'](arg1);
}

export function VizASTDot(arg1) {
  return window['go']['main']['App']['VizASTDot'](arg1);
}

export function VizBlocking(arg1) {
  return window['go']['main']['App']['VizBlocking'](arg1);
}

export function VizEmit(arg1) {
  return window['go']['main']['App']['VizEmit'](arg1);
}

export function VizSymbols(arg1) {
  return window['go']['main']['App']['VizSymbols'](arg1);
}

export function VizSymbolsDot(arg1) {
  return window['go']['main']['App']['VizSymbolsDot'](arg1);
}

export function VizTokens(arg1) {
  return window['go']['main']['App']['VizTokens'](arg1);
}
