package dlg

import (
	"bufio"
	"fmt"
	"hash/fnv"
	"strings"
)

// LocEntry is one localizable string extracted from a dialogue project.
type LocEntry struct {
	LocKey    string // stable key (node:line:hash8)
	NodeTitle string
	Character string // empty for narration
	LineType  string // "spoken" | "choice" | "narration"
	Source    string // original source text
	Language  string // locale code this entry originates from (e.g. "en", "fr"); empty = inherit from project
}

// CollectLocEntries walks a LinkedProject and returns all localizable strings
// in source order (file → node → body).
func CollectLocEntries(lp *LinkedProject) []LocEntry {
	var entries []LocEntry
	for _, f := range lp.Files {
		for _, n := range f.Nodes {
			var lineIdx int
			collectNodeEntries(n, &lineIdx, &entries)
		}
	}
	return entries
}

func collectNodeEntries(n *DialogueNode, lineIdx *int, entries *[]LocEntry) {
	collectStmtEntries(n.Title, n.Language, n.Character, n.Body, lineIdx, entries)
}

func collectStmtEntries(nodeTitle, language, character string, stmts []Statement, lineIdx *int, entries *[]LocEntry) {
	for _, s := range stmts {
		switch st := s.(type) {
		case *SpeakerLine:
			key := st.LocKey
			if key == "" {
				key = autoLocKey(nodeTitle, *lineIdx, st.Text)
			}
			*lineIdx++
			*entries = append(*entries, LocEntry{
				LocKey:    key,
				NodeTitle: nodeTitle,
				Character: st.Speaker,
				LineType:  "spoken",
				Source:    st.Text,
				Language:  language,
			})

		case *NarrationLine:
			key := st.LocKey
			if key == "" {
				key = autoLocKey(nodeTitle, *lineIdx, st.Text)
			}
			*lineIdx++
			*entries = append(*entries, LocEntry{
				LocKey:    key,
				NodeTitle: nodeTitle,
				Character: character,
				LineType:  "narration",
				Source:    st.Text,
				Language:  language,
			})

		case *OptionBranch:
			key := st.LocKey
			if key == "" {
				key = autoLocKey(nodeTitle, *lineIdx, st.Text)
			}
			*lineIdx++
			*entries = append(*entries, LocEntry{
				LocKey:    key,
				NodeTitle: nodeTitle,
				Character: character,
				LineType:  "choice",
				Source:    st.Text,
				Language:  language,
			})
			collectStmtEntries(nodeTitle, language, character, st.Body, lineIdx, entries)
		}
	}
}

// ExportPO produces a gettext PO file string for all entries in the project.
// existingTranslations maps msgctxt → msgstr from a previously exported file;
// when diffOnly is true, entries with a non-empty translation are omitted.
func ExportPO(entries []LocEntry, existingTranslations map[string]string, diffOnly bool) string {
	var sb strings.Builder

	sb.WriteString(`# AGS3D Dialogue Localisation
# This file was generated by 'ag export --locale'.
# msgctxt = stable loc key; msgid = source text; msgstr = translation.
msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

`)

	for _, e := range entries {
		existing := existingTranslations[e.LocKey]
		if diffOnly && existing != "" {
			continue
		}
		msgstr := existing

		charComment := ""
		if e.Character != "" {
			charComment = fmt.Sprintf("\n#. Character: %s", e.Character)
		}
		fmt.Fprintf(&sb, "#. Type: %s\n#. Node: %s%s\nmsgctxt %q\nmsgid %q\nmsgstr %q\n\n",
			e.LineType, e.NodeTitle, charComment, e.LocKey, e.Source, msgstr)
	}

	return sb.String()
}

// ExportCSV produces a CSV string for all entries.
// existingTranslations maps loc_key → translation (may be nil).
// diffOnly omits entries that already have a non-empty translation.
func ExportCSV(entries []LocEntry, existingTranslations map[string]string, diffOnly bool) string {
	var sb strings.Builder
	sb.WriteString("loc_key,node,character,type,source_text,translation\n")

	for _, e := range entries {
		existing := existingTranslations[e.LocKey]
		if diffOnly && existing != "" {
			continue
		}
		fmt.Fprintf(&sb, "%s,%s,%s,%s,%s,%s\n",
			csvField(e.LocKey),
			csvField(e.NodeTitle),
			csvField(e.Character),
			csvField(e.LineType),
			csvField(e.Source),
			csvField(existing),
		)
	}

	return sb.String()
}

// csvField quotes a CSV field if it contains commas, newlines, or quotes.
func csvField(s string) string {
	if strings.ContainsAny(s, ",\"\n\r") {
		return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
	}
	return s
}

// ParsePOTranslations reads an existing PO file and returns a map of
// msgctxt → msgstr for all entries that have a non-empty msgstr.
func ParsePOTranslations(content string) map[string]string {
	result := make(map[string]string)
	scanner := bufio.NewScanner(strings.NewReader(content))

	var ctx, msgstr string
	var inMsgstr bool

	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "msgctxt ") {
			ctx = unquotePOString(strings.TrimPrefix(line, "msgctxt "))
			msgstr = ""
			inMsgstr = false
		} else if strings.HasPrefix(line, "msgstr ") {
			msgstr = unquotePOString(strings.TrimPrefix(line, "msgstr "))
			inMsgstr = true
		} else if inMsgstr && strings.HasPrefix(line, `"`) {
			// Continuation line.
			msgstr += unquotePOString(line)
		} else if line == "" {
			if ctx != "" && msgstr != "" {
				result[ctx] = msgstr
			}
			ctx = ""
			msgstr = ""
			inMsgstr = false
		}
	}
	// Handle last entry without trailing blank line.
	if ctx != "" && msgstr != "" {
		result[ctx] = msgstr
	}
	return result
}

// ParseCSVTranslations reads an existing CSV file and returns a map of
// loc_key → translation for all entries with a non-empty translation column.
func ParseCSVTranslations(content string) map[string]string {
	result := make(map[string]string)
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		if i == 0 || strings.TrimSpace(line) == "" {
			continue // skip header and blank lines
		}
		fields := splitCSVLine(line)
		if len(fields) >= 6 && fields[5] != "" {
			result[fields[0]] = fields[5]
		}
	}
	return result
}

// unquotePOString strips the surrounding quotes and unescapes a PO string literal.
func unquotePOString(s string) string {
	s = strings.TrimSpace(s)
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		s = s[1 : len(s)-1]
	}
	s = strings.ReplaceAll(s, `\"`, `"`)
	s = strings.ReplaceAll(s, `\n`, "\n")
	s = strings.ReplaceAll(s, `\\`, `\`)
	return s
}

// splitCSVLine splits one CSV line respecting quoted fields.
func splitCSVLine(line string) []string {
	var fields []string
	var cur strings.Builder
	inQuote := false
	for i := 0; i < len(line); i++ {
		c := line[i]
		switch {
		case c == '"' && !inQuote:
			inQuote = true
		case c == '"' && inQuote:
			if i+1 < len(line) && line[i+1] == '"' {
				cur.WriteByte('"')
				i++
			} else {
				inQuote = false
			}
		case c == ',' && !inQuote:
			fields = append(fields, cur.String())
			cur.Reset()
		default:
			cur.WriteByte(c)
		}
	}
	fields = append(fields, cur.String())
	return fields
}

// sourceHash returns the first 8 hex digits of an FNV-32a hash of text.
// Used to detect source text changes in the diff pass.
func sourceHash(text string) string {
	h := fnv.New32a()
	_, _ = h.Write([]byte(text))
	return fmt.Sprintf("%08x", h.Sum32())
}

// ValidateLocKeys checks that every explicit loc_key: used in the linked
// dialogue project is present in the provided locale map (key → translated value).
// Returns one ValidationIssue per missing key.
//
// Only lines with an explicit loc_key: annotation are validated; auto-generated
// keys (empty LocKey) are always considered valid.
func ValidateLocKeys(lp *LinkedProject, localeMap map[string]string) []ValidationIssue {
	var issues []ValidationIssue
	for _, f := range lp.Files {
		for _, n := range f.Nodes {
			validateNodeLocKeys(n, &issues, localeMap)
		}
	}
	return issues
}

func validateNodeLocKeys(n *DialogueNode, issues *[]ValidationIssue, localeMap map[string]string) {
	validateStmtLocKeys(n.Title, n.Body, issues, localeMap)
}

func validateStmtLocKeys(nodeTitle string, stmts []Statement, issues *[]ValidationIssue, localeMap map[string]string) {
	for _, s := range stmts {
		switch st := s.(type) {
		case *SpeakerLine:
			if st.LocKey != "" {
				if _, ok := localeMap[st.LocKey]; !ok {
					*issues = append(*issues, ValidationIssue{
						Pos:    st.SrcPos,
						LocKey: st.LocKey,
						Msg:    fmt.Sprintf("dialogue node %q: loc_key %q not found in locale file", nodeTitle, st.LocKey),
					})
				}
			}
		case *NarrationLine:
			if st.LocKey != "" {
				if _, ok := localeMap[st.LocKey]; !ok {
					*issues = append(*issues, ValidationIssue{
						Pos:    st.SrcPos,
						LocKey: st.LocKey,
						Msg:    fmt.Sprintf("dialogue node %q: loc_key %q not found in locale file", nodeTitle, st.LocKey),
					})
				}
			}
		case *OptionBranch:
			if st.LocKey != "" {
				if _, ok := localeMap[st.LocKey]; !ok {
					*issues = append(*issues, ValidationIssue{
						Pos:    st.SrcPos,
						LocKey: st.LocKey,
						Msg:    fmt.Sprintf("dialogue node %q: loc_key %q not found in locale file", nodeTitle, st.LocKey),
					})
				}
			}
			validateStmtLocKeys(nodeTitle, st.Body, issues, localeMap)
		}
	}
}

// ValidationIssue represents a localisation validation error with source location.
type ValidationIssue struct {
	Pos    Pos
	LocKey string
	Msg    string
}
