// embed_scripts generates C++ string constants for AGS3D GDScript runtime files.
// Run: cd tools/embed_scripts && go run .
//
// It reads all .gd files from game_prototype/.engine/runtime/ and generates:
//   - embedded_scripts.h: declarations
//   - embedded_scripts.cpp: string constants + registration calls
//   - Copies both files to modules/agvm/
//
// These files are included in the agvm C++ module to embed the runtime GDScripts
// into the Godot binary (T-FINAL).
package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const runtimeDir = "game_prototype/.engine/runtime/"

func main() {
	files, err := filepath.Glob(runtimeDir + "*.gd")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	var scripts []struct {
		path   string
		name   string
		source string
	}

	for _, f := range files {
		name := filepath.Base(f)
		data, err := os.ReadFile(f)
		if err != nil {
			fmt.Fprintln(os.Stderr, "reading", f, ":", err)
			os.Exit(1)
		}
		constName := toConstName(name)
		scripts = append(scripts, struct {
			path   string
			name   string
			source string
		}{
			path:   "res://.engine/runtime/" + name,
			name:   constName,
			source: string(data),
		})
	}

	genHeader(scripts)
	genCPP(scripts)

	if err := copyFile("embedded_scripts.h", "modules/agvm/embedded_scripts.h"); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := copyFile("embedded_scripts.cpp", "modules/agvm/embedded_scripts.cpp"); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Printf("Generated and copied embedded_scripts.h and embedded_scripts.cpp for %d runtime GDScripts\n", len(scripts))
}

func copyFile(src, dst string) error {
	f, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("open %s: %w", src, err)
	}
	defer f.Close()
	g, err := os.Create(dst)
	if err != nil {
		return fmt.Errorf("create %s: %w", dst, err)
	}
	defer g.Close()
	if _, err := io.Copy(g, f); err != nil {
		return fmt.Errorf("copy %s -> %s: %w", src, dst, err)
	}
	return nil
}

func toConstName(filename string) string {
	name := strings.TrimSuffix(filename, ".gd")
	name = strings.ReplaceAll(name, "_", "")
	// PascalCase: uppercase first letter
	name = strings.ToUpper(name[:1]) + name[1:]
	return name
}

func genHeader(scripts []struct {
	path   string
	name   string
	source string
}) {
	f, err := os.Create("embedded_scripts.h")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprintln(f, "// GENERATED BY tools/embed_scripts — DO NOT EDIT")
	fmt.Fprintln(f, "#pragma once")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "// Embedded GDScript runtime sources.")
	fmt.Fprintf(f, "// Count: %d\n", len(scripts))
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "void register_embedded_scripts(ResourceFormatLoaderAGSEmbed *loader);")
}

func genCPP(scripts []struct {
	path   string
	name   string
	source string
}) {
	f, err := os.Create("embedded_scripts.cpp")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprintln(f, "// GENERATED BY tools/embed_scripts — DO NOT EDIT")
	fmt.Fprintln(f, "// Embeds all AGS3D runtime GDScripts as C++ string constants.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "#include \"ags_embed_loader.h\"")
	fmt.Fprintln(f, "")

	for _, s := range scripts {
		constName := s.name + "SRC"
		// Use raw string literal R"AGS3D(... )AGS3D" with delimiter AGS3D.
		// This is safe: GDScript source never contains )AGS3D" so cannot
		// accidentally close the string.
		fmt.Fprintf(f, "static const char *%s = R\"AGS3D(%s)AGS3D\";\n", constName, s.source)
	}

	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "void register_embedded_scripts(ResourceFormatLoaderAGSEmbed *loader) {")

	for _, s := range scripts {
		constName := s.name + "SRC"
		relPath := s.path
		fmt.Fprintf(f, "\tloader->register_script(%q, %s);\n", relPath, constName)
	}

	fmt.Fprintln(f, "}")
}
